<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.pig4cloud</groupId>
		<artifactId>pig-common</artifactId>
		<version>${revision}</version>
	</parent>

	<artifactId>pig-common-warehouse</artifactId>

	<properties>
		<maven.compiler.source>21</maven.compiler.source>
		<maven.compiler.target>21</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<!-- common -->
		<dependency>
			<groupId>com.pig4cloud</groupId>
			<artifactId>pig-common-core</artifactId>
			<scope>provided</scope>
		</dependency>
		<!-- mybatis plus -->
		<dependency>
			<groupId>com.pig4cloud</groupId>
			<artifactId>pig-common-mybatis</artifactId>
		</dependency>
		<!-- plugin -->
		<dependency>
			<groupId>com.pig4cloud</groupId>
			<artifactId>pig-common-plugin</artifactId>
			<scope>provided</scope>
		</dependency>
		<!-- util -->
		<dependency>
			<groupId>commons-net</groupId>
			<artifactId>commons-net</artifactId>
		</dependency>
		<!-- spring -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-autoconfigure</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
		<!-- taos-jdbc driver -->
		<dependency>
			<groupId>com.taosdata.jdbc</groupId>
			<artifactId>taos-jdbcdriver</artifactId>
			<version>${taos-jdbcdriver.version}</version>
		</dependency>
		<!-- IoTDB -->
		<dependency>
			<groupId>org.apache.iotdb</groupId>
			<artifactId>iotdb-session</artifactId>
			<version>${iotdb-session.version}</version>
			<exclusions>
				<exclusion>
					<artifactId>commons-io</artifactId>
					<groupId>commons-io</groupId>
				</exclusion>
				<exclusion>
					<artifactId>snappy-java</artifactId>
					<groupId>org.xerial.snappy</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<!-- influxdb Here, support for version 1.7, use influxdb-java, Full support for version 2.x requires influxdb-client-java -->
		<dependency>
			<groupId>org.influxdb</groupId>
			<artifactId>influxdb-java</artifactId>
			<version>${influxdb.version}</version>
		</dependency>
		<!-- greptimedb -->
		<dependency>
			<groupId>io.greptime</groupId>
			<artifactId>ingester-all</artifactId>
			<version>${greptimedb.version}</version>
			<exclusions>
				<exclusion>
					<groupId>io.grpc</groupId>
					<artifactId>grpc-all</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.google.code.gson</groupId>
					<artifactId>gson</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.google.guava</groupId>
					<artifactId>guava</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.google.protobuf</groupId>
					<artifactId>protobuf-java</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<!-- kafka -->
		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka-clients</artifactId>
			<exclusions>
				<exclusion>
					<artifactId>snappy-java</artifactId>
					<groupId>org.xerial.snappy</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<!--redis-->
		<dependency>
			<groupId>io.lettuce</groupId>
			<artifactId>lettuce-core</artifactId>
			<scope>provided</scope>
		</dependency>
		<!-- swagger -->
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.arrow</groupId>
			<artifactId>arrow-vector</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.arrow</groupId>
			<artifactId>arrow-memory-netty</artifactId>
		</dependency>

		<dependency>
			<groupId>org.xerial.snappy</groupId>
			<artifactId>snappy-java</artifactId>
			<version>${snappy-java.version}</version>
		</dependency>
	</dependencies>
</project>
