<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.pig4cloud</groupId>
		<artifactId>pig-common</artifactId>
		<version>${revision}</version>
	</parent>

	<artifactId>pig-common-grafana</artifactId>

	<properties>
		<maven.compiler.source>21</maven.compiler.source>
		<maven.compiler.target>21</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven-jar-plugin.version>3.2.0</maven-jar-plugin.version>
		<maven-assembly-plugin.version>3.3.0</maven-assembly-plugin.version>
	</properties>

	<dependencies>
		<!-- hertzbeat common -->
		<dependency>
			<groupId>com.pig4cloud</groupId>
			<artifactId>pig-common-core</artifactId>
		</dependency>
		<!-- hertzbeat warehouse -->
		<dependency>
			<groupId>com.pig4cloud</groupId>
			<artifactId>pig-common-warehouse</artifactId>
		</dependency>
		<!-- jpa -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<!-- swagger -->
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
		</dependency>
	</dependencies>
</project>
